language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
script: make ci
jobs:
  include:
    - if: type != pull_request AND branch = master
      stage: Publish to NPM
      script: yarn semantic-release
